%% Chapter 6: Some Statistics in MATLAB

%% 6.1 Probability Density Function (PDF) 
%PDF can be used to plot the density functions. 
x = linspace(-10,10,1000);
y1 = normpdf(x,0,1);  
y2 = normpdf(x, 0, 3); 
y3 = normpdf(x, 4,1); 

subplot(1,2,1)
plot(x,y1,'b')
hold on
plot(x,y2,'r') 
hold off
legend('N(0,1)', 'N(0,3)')

subplot(1,2,2) 
plot(x,y1, 'b') 
hold on 
plot(x,y3, 'r') 
hold off
legend('N(0,1)', 'N(4,1)')


%% For discretre random variables, PDF also can be used to calculate probabilities
%Ex. Toss a fair coin 10 times. What is the probability of getting 3 heads?
nchoosek(10,3)*(0.5^3)*(0.5^7) 
binopdf(3, 10, 0.5)

%help stats to see all density functions
%Generical structure of the pdf functions is: Distribution name and then pdf 


%% 6.2.1 Cumulative Distribution Function (CDF)- Solution
%Computation in MATLAB 

% P(X <= 1.1), X is standard normal. 
normcdf(1.1, 0, 1)
normcdf(1.1)
%Don't have to standardize [ P(X <= 6.4), X was N(2,4) ]
normcdf(6.4, 2, 4)

%Computation with table
% http://z-scoretable.com/ 

% Computation with Casio calculator 
% https://www.manualslib.com/manual/221260/Casio-Fx-9750gii.html?page=180#manual 
%Notice, parameters in different order than in MATLAB. 

%% Ex. Toss a fair coin 10 times. What is the probability of getting 0,1,2 or 3 heads?
a0 = nchoosek(10,0)*(0.5^0)*(0.5^10);
a1 = nchoosek(10,1)*(0.5^1)*(0.5^9);
a2 = nchoosek(10,2)*(0.5^2)*(0.5^8); 
a3 = nchoosek(10,3)*(0.5^3)*(0.5^7); 

probability = a0 + a1 + a2 + a3 

binocdf(3, 10, 0.5) % Much faster
 
% help stats 

%% 6.3.1 Quantile - Example 
%Find upper 0.025 quantile of N(0,1) 
norminv(1-0.025, 0, 1)
%0.025 to the right --> 0.975 to the left. Double check: 
normcdf(1.96, 0, 1)

%help stats to see a complete list 
% Generical structure is: distribution name and then inv

% For other (discrete distributions) such as poisson distribution, read documentation
% of what it does. 
doc poissoninv

%% 6.4 (Pseudo)Random numbers
% "Pseudorandom numbers are generated by deterministic algorithms.
% They are "random" in the sense that, on average, they pass statistical tests 
% regarding their distribution and correlation. They differ from true random numbers
% in that they are generated by an algorithm, rather than a truly random
% process." 
% % % Source: https://se.mathworks.com/help/stats/generating-random-data.html

% For practical purposes, we view the generated numbers as completly random. 

rand %Uniformly distributed random number in the interval (0,1) 
rand(3)  

normrnd(10,2,3,5)   
randn(2,5) %Standard normal
binornd(10,0.7, 2,3)  

%help stats
%% 6.5  Fitting a Distribution to Data - Histfit, Probplot
x = exprnd(3, 400,1);
%Assume that we don't know from which distribution the observations come form.  
%Now we will use graphical techniques to find a suitable distribution for the data

%hist and histfit
hist(x)
histfit(x)
histfit(x, 20, 'exponential')


%Another graphical technique matches the quantiles of sample data 
%to the quantiles of a given probability distribution. It is often called
%probability plot or QQ-plot. 

subplot(1,3,1) 
probplot('normal', x) 
subplot(1,3,2) 
normplot(x)
subplot(1,3,3) 
probplot(x) 
probplot('exponential', x) 


% doc histfit 
% doc probplot

%% 6.5.1 Parameter Estimation - Fitdist
fitdist(x, 'exponential')

% doc fitdist

%% 6.6 Correlation Coefficient

%(Pearson) Correlation Coefficient 
% Measures direction (Positive/Negative) and strength (Strong/Weak),of the Linear 
% Relationship between two random variables, lies between [-1,1]. 
% Correlation of a random variable with itself is 1.

%Simulate 100 observations of two random variables from a MVN distribution.

%Resulting in a 100 x 2 matrix (each row is a observation of the random variables). 
rho = -0.99
X = mvnrnd([0 0], [1 rho;rho 1], 100);  

% Don't focus on the MVN, pretend that the data comes from some experiment
% and we shall now try to do some educated guesses. 

plot(X(:,1),X(:,2),'.') %Positive/negative, strong/weak? 

corrcoef(X) %Correlation coefficient matrix 
%columns represent random variables,rows represent observations of the random variable.

% possible to obtain confidence intervals aswell
% doc corrcoef